version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: job_scraper_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: job_scraper
      MYSQL_USER: jobuser
      MYSQL_PASSWORD: jobpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - job_scraper_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: job_scraper_backend
    restart: always
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: jobuser
      MYSQL_PASSWORD: jobpass
      MYSQL_DATABASE: job_scraper
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend:/app
    networks:
      - job_scraper_network

volumes:
  mysql_data:

networks:
  job_scraper_network:
    driver: bridge